OZO 「お象」: Functions
Functions
Core
Description
Core utility functions of the library.
Functions
template<typename T >
decltype(auto) constexpr ozo::is_null (const T &v) noexcept(noexcept(is_null_impl< T >::apply(v)))
Indicates if value is in null state.
template<typename T , typename Alloc >
void ozo::allocate_nullable (T &out, const Alloc &a)
Allocates nullable object of given type.
template<typename T >
decltype(auto) constexpr ozo::unwrap_recursive (T &&v) noexcept
Unwraps argument underlying value recursively.
template<typename T >
constexpr bool ozo::is_null_recursive (T &&v) noexcept
Indicates if one of unwrapped values is in null state.
template<typename T >
decltype(auto) constexpr ozo::unwrap (T &&v) noexcept(noexcept(unwrap_impl< std::decay_t< T >>::apply(std::forward< T >(v))))
Unwraps argument underlying value or forwards the argument.
Function Documentation
allocate_nullable()
template<typename T , typename Alloc > void ozo::allocate_nullable (T & out, const Alloc & a)
Allocates nullable object of given type.
This function allocates memory and constructs nullable object of given type by means of given allocator if applicable. It uses ozo::allocate_nullable_impl functional object as an implementation.
Note
The function implementation may use no allocator and ignore the argument (e.g.: if it is not applicable to the given object type).
Parameters
out — object to allocate to
a — allocator to use
is_null()
template<typename T > decltype(auto) constexpr ozo::is_null (const T & v) noexcept
Indicates if value is in null state.
This utility function indicates if given value is in null state. If argument is not Nullable it always returns false
Parameters
value — object to examine
Returns
true — object is in null-state,
false — overwise.
Referenced by ozo::send(), and ozo::size_of().
is_null_recursive()
template<typename T > constexpr bool ozo::is_null_recursive (T && v) noexcept
Indicates if one of unwrapped values is in null state.
This utility function recursively examines the value for a null state. The function is useful to examine Connection object for a null state because it is normal for such object to be wrapped.
The function is equal to this pesudo-code:
constexpr bool is_null_recursive(auto&& arg) noexcept {
    while (decltype(arg) != unwrap_type<decltype(arg)>) {
        if (is_null(arg)) {
            return true;
        }
        arg = unwrap(arg);
    }
    return false;
}
Parameters
v — object to examine
Returns
true — one of the objects is in null-state,
false — overwise.
See also
ozo::is_null(), ozo::unwrap()
Referenced by ozo::connection_bad(), and ozo::error_message().
unwrap()
template<typename T > decltype(auto) constexpr ozo::unwrap (T && v) noexcept
Unwraps argument underlying value or forwards the argument.
This utility function returns underlying value of it's argument as defined by the operation implementation ozo::unwrap_impl.
In-library implementations returns:
reference on an underlying value - std::reference_wrapper and other types like pointers, optional values which are defined via Extentions,
argument itself by default.
Parameters
value — object to unwrap
Returns
implementation depended result of unwrap_impl<std::decay_t<T>>::apply(std::forward<T>(v)) call
Referenced by ozo::send(), and ozo::size_of().
unwrap_recursive()
template<typename T > decltype(auto) constexpr ozo::unwrap_recursive (T && v) noexcept
Unwraps argument underlying value recursively.
This utility function unwraps argument recursively applying ozo::unwrap() function until the type of unwrapped value and type of it's argument become the same.
Note
Before applying the function it is better to check the object recursively for a null state via ozo::is_null_recursive().
The function is equal to this pesudo-code:
constexpr decltype(auto) unwrap_recursive(auto&& arg) noexcept {
    while (decltype(arg) != unwrap_type<decltype(arg)>) {
        arg = unwrap(arg);
    }
    return arg;
}
Parameters
value — object to unwrap
Returns
implementation depended result of recursively applied ozo::unwrap()
See also
ozo::is_null_recursive()